services:
  - type: web
    name: hawkeye-lbw
    env: docker
    context: ./Cricket Hawkeye
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    disk:
      name: hawkeye-uploads-storage
      mountPath: /app/static/uploads
      sizeGB: 1
