services:
  - type: web
    name: hawkeye-lbw
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
