services:
  - type: web
    name: hawkeye-lbw
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free # Agar free use karna hai, paid ke liye 'standard' rehne dein
    region: oregon # Render ka standard stable region
    disk:
      name: hawkeye-uploads-storage
      mountPath: /app/static/uploads
      sizeGB: 1
